version: '3.8'

services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_data:/app/instance
    environment:
      - FLASK_ENV=development
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  backend_data:

networks:
  todo-network:
    driver: bridge